# PENGERTIAN NUMPY

Numpy adalah paket dasar untuk komputasi ilmiah dalam bahasa Python(NumPy is the fundamental package for scientific computing in Python)

# ARRAY NUMPY

Membuat Array Numpy

In [1]:
import numpy as np

In [2]:
#Membuat Array
nilai_siswa = np.array([85,55,40,90])

In [3]:
#Mengakses data pada Array
print(nilai_siswa[3])

90


# MATRIX NUMPY

Membuat Matrix tanpa numpy

In [4]:
matrix = [[1,2,3],
         [4,5,6],
         [7,8,9]]

Membuat Matrix dengan numpy

In [5]:
matrix_np = np.array([[1,2,3],[4,5,6],[7,8,9]])

Mengakses data Matrix dengan numpy

In [6]:
print(matrix_np[1][1])

5


In [7]:
print(matrix_np[0][2])

3


# OPERASI MATRIX DENGAN NUMPY

Penjumlahan

In [11]:
import numpy as np 

In [14]:
matrik_a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [17]:
matrix_b = np.array([[3,2,1],[6,5,4],[9,8,7]])

In [20]:
hasil = matrik_a + matrix_b
print(hasil)

[[ 4  4  4]
 [10 10 10]
 [16 16 16]]


Pengurangan

In [21]:
matrik_a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [22]:
matrix_b = np.array([[3,2,1],[6,5,4],[9,8,7]])

In [23]:
hasil = matrik_a - matrix_b
print(hasil)

[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]


Perkalian

In [24]:
matrik_a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [25]:
matrix_b = np.array([[3,2,1],[6,5,4],[9,8,7]])

In [26]:
hasil = matrik_a * matrix_b
print(hasil)

[[ 3  4  3]
 [24 25 24]
 [63 64 63]]


Pembagian

In [27]:
matrik_a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [28]:
matrix_b = np.array([[3,2,1],[6,5,4],[9,8,7]])

In [29]:
hasil = matrik_a / matrix_b
print(hasil)

[[0.33333333 1.         3.        ]
 [0.66666667 1.         1.5       ]
 [0.77777778 1.         1.28571429]]


# TRANSPOSE MATRIX DENGAN NUMPY

In [30]:
import numpy as np 

In [31]:
matrix_a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
print("Matrix awal: ")
print(matrix_a)

Matrix awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
hasil = matrix_a.transpose()
print("Matrix kebalikan: ")
print(hasil)

Matrix kebalikan: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# MENGUBAH BENTUK UKURAN MATRIX

In [34]:
import numpy as np

In [35]:
matrix_a = np.array([1,2,3,4,5,6])

In [37]:
print("Matrix awal: ")
print(matrix_a)
print("Ukuran = ", matrix_a.shape)

Matrix awal: 
[1 2 3 4 5 6]
Ukuran =  (6,)


In [38]:
hasil = matrix_a.reshape(3,2)
print("Mengubah ke 3x2: ")
print(hasil)
print("Ukuran = ",hasil.shape)

Mengubah ke 3x2: 
[[1 2]
 [3 4]
 [5 6]]
Ukuran =  (3, 2)


# MENGUBAH MATRIX KE LIST VEKTOR

In [39]:
import numpy as np

In [45]:
matrix_a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [46]:
print("Matrix awal: ")
print(matrix_a)
print("Ukuran = ", matrix_a.shape)

Matrix awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ukuran =  (3, 3)


In [42]:
hasil = matrix_a.flatten()

In [47]:
print("Matrix setelah di-flatten: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrix setelah di-flatten: 
[1 2 3 4 5 6 7 8 9]
Ukuran =  (9,)


# FUNGSI PENGOLAHAN DATA DI NUMPY 

In [48]:
import numpy as np

In [49]:
nilai_siswa = np.array([55,43,98,76,65,77,65,90])

In [50]:
print("Nilai maksimal = ", nilai_siswa.max())

Nilai maksimal =  98


In [51]:
print("Nilai rata-rata = ", nilai_siswa.mean())

Nilai rata-rata =  71.125


In [52]:
print("Total nilai = ", nilai_siswa.sum())

Total nilai =  569


In [53]:
print("Standar Deviasi = ", nilai_siswa.std())

Standar Deviasi =  16.81842367762211


In [54]:
print("Nilai minimal = ", nilai_siswa.min())

Nilai minimal =  43


# COPY & VIEWS ARRAY DI NUMPY

Perbedaan copy dan views

copy : perubahan tidak akan mempengaruhi array aslinya
views : perubahan akan mempengaruhi array aslinya

In [55]:
import numpy as np

In [56]:
arr = np.array([1,2,3,4,5])

In [58]:
#copy array menggunakan metode copy()
arr_copy = arr.copy()

In [59]:
#Membuat view array menggunakan metode view()
arr_view = arr.view()

In [60]:
#Mengubah elemen pada array asli
arr[0] = 10

In [61]:
#Menampilkan array asl,copy,dan view
print("Array asli: ",arr)
print("Array copy: ",arr_copy)
print("Array view: ",arr_view)

Array asli:  [10  2  3  4  5]
Array copy:  [1 2 3 4 5]
Array view:  [10  2  3  4  5]
